version: "3"

services:
  minecraft:
    image: skyblue3350/minecraft-forge
    build: ./
    ports:
      - 25565:25565
    environment:
      - EXTRA_ARG=
    volumes:
      - ./mod:/mc/mods
      - ./world:/mc/world

