version: "3"

services:
  minecraft:
    image: skyblue3350/minecraft-forge
    restart: always
    ports:
      - 25565:25565
    environment:
      - EXTRA_ARG=nogui
    volumes:
      - ./mod:/mc/mod
      - ./world:/mc/world

